//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biblioteca_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class entrada
    {
        public int cod_entrada { get; set; }
        public string titulo { get; set; }
        public string contenido { get; set; }
        public Nullable<System.DateTime> fecha_entrada { get; set; }
        public Nullable<System.DateTime> fecha_publicacion { get; set; }
        public string UserId { get; set; }
        public string meta { get; set; }
        public string portada { get; set; }
        public Nullable<int> id_archivo { get; set; }
        public string estado { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual docs docs { get; set; }
        public virtual estado estado1 { get; set; }
    }
}
